#!/bin/sh
# This script is only used for developement. It is removed by the 
# distribution process. 

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -classic-display -use-ocamlfind"}

action () 
{
    case $1 in
        default) $OCAMLBUILD gg.cmx gg.cmo ;;
        tests)   $OCAMLBUILD test/tests.otarget ;;
        doc)     shift; devel/pkg-doc $* doc/api.docdir ;;
        distrib) devel/pkg-distrib ;;
        publish) devel/pkg-www ;;
        publish-opam) devel/pkg-opam ;;
        clean)        $OCAMLBUILD -clean ;;
        *)            $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ]; 
then action default ; 
else action $*; fi
